
SET SERVEROUTPUT ON 
ALTER TABLE SRE_JOB DISABLE CONSTRAINT SRE_R_2;
ALTER TABLE SRE_NODE DISABLE CONSTRAINT SRE_R_24;
DELETE FROM SRE_NODE CASCADE;
DELETE FROM sre_job_queue_metrics;
DELETE FROM SRE_JOB_TRACE CASCADE;
DELETE FROM SRE_JOB_SUMMARY_EXT CASCADE;
DELETE FROM SRE_JOB_SUMMARY CASCADE;
DELETE FROM SRE_JOB CASCADE;
UPDATE SRE_GLOBAL_PROPERTY SET VALUE=NULL WHERE NAME='NODEASSIGNEMENTLOCK';
COMMIT;
EXIT;
